[Service]
WorkingDirectory=/var/rootdirs/home/weston
SupplementaryGroups=render video
ExecStart=
ExecStart=/usr/bin/weston --drm-device=card2 --config=/etc/xdg/weston/waydroid-screen.ini --modules=systemd-notify.so --log=/var/rootdirs/home/weston/weston.log
