[Unit]
Requires=waydroid-image-provision.service
Wants=docker.service
After=waydroid-image-provision.service dbus.service docker.service
PartOf=docker.service
ConditionPathExists=/var/lib/waydroid/waydroid.cfg

[Service]
ExecStartPre=/usr/libexec/waydroid-frdm-prepare
Restart=on-failure
RestartSec=5
TimeoutStopSec=45
