#!/bin/bash
# SPDX-License-Identifier: MIT
set -euo pipefail

repo="$(cd "$(dirname "$0")/.." && pwd)"
files="$repo/recipes-support/waydroid/waydroid"
recipe="$repo/recipes-support/waydroid/waydroid.bbappend"
prepare="$files/waydroid-frdm-prepare"
permissions="$files/waydroid-frdm-device-permissions"
container_dropin="$files/waydroid-frdm-container.conf"
legacy_container_input="$files/waydroid-frdm-container.service"
session_service="$files/waydroid-frdm-session.service"
ui_service="$files/waydroid-frdm-ui.service"
show_ui="$files/waydroid-frdm-show-ui"
network_ready="$files/waydroid-frdm-network-ready"
network_script="$files/waydroid-net.sh"
weston_gbm_dropin="$files/20-frdm-gbm.conf"
apparmor_patch="$files/0004-apparmor-allow-android-resource-cache.patch"
apparmor_property_patch="$files/0005-apparmor-allow-waydroid-property-update.patch"
kernel_recipe="$repo/recipes-kernel/linux/linux-lmp-fslc-imx_6.12.bb"
kernel_config="$repo/recipes-kernel/linux/linux-lmp-fslc-imx/imx95-15x15-lpddr4x-frdm.cfg"
dmabuf_patch="$repo/recipes-kernel/linux/linux-lmp-fslc-imx/0007-dma-buf-add-NXP-i.MX-helper.patch"
mali_recipe="$repo/recipes-graphics/mali/mali-imx_%.bbappend"

sh -n "$prepare"
sh -n "$permissions"
sh -n "$network_ready"
sh -n "$network_script"
python3 -c 'import pathlib, sys; compile(pathlib.Path(sys.argv[1]).read_text(), sys.argv[1], "exec")' "$show_ui"
grep -Fqx 'ExecStartPre=/usr/libexec/waydroid-frdm-prepare' "$container_dropin"
grep -Fqx 'Wants=docker.service' "$container_dropin"
grep -Fqx 'PartOf=docker.service' "$container_dropin"
grep -Fqx 'After=waydroid-image-provision.service dbus.service docker.service' "$container_dropin"
test -s "$legacy_container_input"
grep -Fq 'file://waydroid-frdm-container.service' "$recipe"
grep -Fq 'rm -f ${D}${systemd_system_unitdir}/waydroid-frdm-container.service' "$recipe"
grep -Fqx 'Requires=waydroid-container.service waydroid-frdm-dbus.service weston.service' "$session_service"
grep -Fqx 'ExecStartPost=+/usr/libexec/waydroid-frdm-device-permissions' "$session_service"
test "$(grep -n 'ExecStartPost=+' "$session_service" | sed -n '1p' | cut -d: -f2-)" = \
    'ExecStartPost=+/usr/libexec/waydroid-frdm-network-ready'
test "$(grep -n 'ExecStartPost=+' "$session_service" | sed -n '2p' | cut -d: -f2-)" = \
    'ExecStartPost=+/usr/libexec/waydroid-frdm-device-permissions'
grep -Fqx 'ExecStartPost=+/usr/libexec/waydroid-frdm-network-ready' "$session_service"
grep -Fqx 'TimeoutStartSec=180' "$session_service"
grep -Fqx 'User=weston' "$session_service"
grep -Fqx 'User=fio' "$ui_service"
grep -Fqx 'ExecStartPre=+/usr/bin/waydroid container unfreeze' "$ui_service"
grep -Fqx 'ExecStart=/usr/libexec/waydroid-frdm-show-ui' "$ui_service"
grep -Fq 'file://waydroid-frdm-prepare' "$recipe"
grep -Fq 'file://waydroid-frdm-device-permissions' "$recipe"
grep -Fq 'file://waydroid-frdm-network-ready' "$recipe"
grep -Fq 'file://0004-apparmor-allow-android-resource-cache.patch' "$recipe"
grep -Fq 'file://0005-apparmor-allow-waydroid-property-update.patch' "$recipe"
grep -Fq 'file://waydroid-frdm-show-ui' "$recipe"
grep -Fq 'replace_property ro.hardware.egl mali' "$prepare"
grep -Fq 'replace_property ro.hardware.vulkan mali' "$prepare"
grep -Fq 'replace_property ro.hardware.gralloc arm' "$prepare"
grep -Fq 'replace_property service.sf.prime_shader_cache 0' "$prepare"
grep -Fq 'replace_property debug.hwui.use_buffer_age false' "$prepare"
grep -Fq 'replace_property debug.hwui.render_dirty_regions false' "$prepare"
grep -Fq 'replace_property debug.hwui.enable_partial_updates false' "$prepare"
grep -Fq 'replace_property debug.hwui.use_partial_updates false' "$prepare"
grep -Fqx 'Environment=WESTON_MODULE_MAP=libgbm.so=/usr/lib/libgbm.so.1' "$weston_gbm_dropin"
grep -Fqx 'ExecStartPre=/usr/bin/install -d -m 0700 -o root -g root /run/user/0' "$weston_gbm_dropin"
grep -Fq 'file://20-frdm-gbm.conf' "$recipe"
grep -Fq '${systemd_system_unitdir}/weston.service.d/20-frdm-gbm.conf' "$recipe"
grep -Fq 'FILES:${PN}-libgbm:append:imx95-frdm-evk = " ${libdir}/libgbm${SOLIBSDEV}"' "$mali_recipe"
grep -Fq 'FILES:${PN}-libgbm-dev:remove:imx95-frdm-evk = "${libdir}/libgbm${SOLIBSDEV}"' "$mali_recipe"
if grep -Fq 'replace_property ro.hardware.gralloc default' "$prepare"; then
    echo 'legacy CPU-readback gralloc mode is still selected' >&2
    exit 1
fi
grep -Fq 'remove_property debug.stagefright.ccodec' "$prepare"
grep -Fq 'dev/dma_heap/reserved none bind,create=file' "$prepare"
grep -Fq 'dev/dma_heap/reserved-uncached' "$prepare"
grep -Fq 'dev/dma_heap/system-uncached' "$prepare"
grep -Fq 'test -c /dev/dmabuf_imx' "$prepare"
grep -Fq 'dev/dmabuf_imx dev/dmabuf_imx' "$prepare"
grep -Fq 'lxc.cgroup2.devices.allow = c ${dmabuf_major}:* rwm' "$prepare"
grep -Fq 'chmod 0666 /dev/dma_heap/linux,cma /dev/dma_heap/linux,cma-uncached /dev/dma_heap/system' "$prepare"
grep -Fq 'lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH' "$permissions"
grep -Fq 'chown 0:1006 /dev/video0 /dev/video1 /dev/video2 /dev/video3' "$permissions"
grep -Fq 'chmod 0666 /dev/dma_heap/linux,cma /dev/dma_heap/linux,cma-uncached /dev/dma_heap/system' "$permissions"
grep -Fq '/system/bin/chmod 0666 /dev/dma_heap/reserved' "$permissions"
grep -Fq '/dev/dma_heap/reserved-uncached /dev/dma_heap/system-uncached' "$permissions"
grep -Fq 'chmod 0666 /dev/dmabuf_imx' "$permissions"
grep -Fq 'systemctl is-active --quiet waydroid-container.service' \
    "$repo/test-plan/interface-test-imx95-frdm-evk.sh"
grep -Fq 'file://0007-dma-buf-add-NXP-i.MX-helper.patch' "$kernel_recipe"
grep -Fqx 'CONFIG_DMABUF_IMX=y' "$kernel_config"
grep -Fq 'device_create(dmabuf_class, NULL, dmabuf_dev_imx, NULL, "dmabuf_imx")' "$dmabuf_patch"
grep -Fq '/data/resource-cache/** r,' "$apparmor_patch"
grep -Fq '/vendor/waydroid.prop rw,' "$apparmor_property_patch"
grep -Fq 'IPTABLES_BIN="$(command -v iptables)"' "$network_script"
grep -Fq 'IP6TABLES_BIN="$(command -v ip6tables)"' "$network_script"
! sed -n '/^IPTABLES_BIN=/,/^fi$/p' "$network_script" | head -1 | grep -q iptables-legacy
grep -Fq 'getprop init.svc.netd' "$network_ready"
grep -Fq 'mount -o remount,rw /proc/sys/net' "$network_ready"
grep -Fq "grep -q ' /proc/sys/net rw,' /proc/self/mountinfo" "$network_ready"

echo 'FRDM Waydroid acceleration source check passed'
